### ISSUE TITLE
SWXMLHash / Xcode 9

### ISSUE THREAD

**Issue by MakiCodes** [gca3020/GABoardGameGeek#8]
Hi there,

with the recent version of SWXMLHash it doesn't work anymore.
GABoardGameGeek has a dependency to SWXMLHash and requires 3.0.0 (SWXMLHash ~> '3.0.0'). 
But the recent version of SWXMLHash is 4.0.0.
So could you update the repo so that its supporting SWXMLHash 4.0.0?

Thanks!

**Comment by toobiz** [comment]
Hi @MakiCodes,
I have just upgraded the repo to support SWXMLHash 4.7.0
Enjoy!

**Comment by gca3020** [comment]
Thanks to @toobiz for making these updates to a long-neglected (by me) library. I'm fixing the CI build and creating a new tag. Thanks!

**Comment by gca3020** [comment]
Marking this as resolved. The 1.1.0 version should support current dependencies.
